"""fase5_ventas

Revision ID: 1509f2049f95
Revises: 1d260ba71b00
Create Date: 2026-07-23 16:21:12.097612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1509f2049f95'
down_revision: Union[str, None] = '1d260ba71b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', name='metodopago'), nullable=False),
    sa.Column('total_venta', sa.Integer(), nullable=False),
    sa.Column('total_neto', sa.Integer(), nullable=False),
    sa.Column('total_iva', sa.Integer(), nullable=False),
    sa.Column('costo_total', sa.Integer(), nullable=False),
    sa.Column('ganancia', sa.Integer(), nullable=False),
    sa.Column('anulada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_fecha_hora'), 'ventas', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_ventas_negocio_id'), 'ventas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_ventas_usuario_id'), 'ventas', ['usuario_id'], unique=False)
    op.create_table('venta_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_items_producto_id'), 'venta_items', ['producto_id'], unique=False)
    op.create_index(op.f('ix_venta_items_venta_id'), 'venta_items', ['venta_id'], unique=False)
    op.create_table('detalle_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('venta_item_id', sa.Integer(), nullable=False),
    sa.Column('producto_vendido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario_venta', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_stock.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['producto_vendido_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.ForeignKeyConstraint(['venta_item_id'], ['venta_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_ventas_lote_id'), 'detalle_ventas', ['lote_id'], unique=False)
    op.create_index(op.f('ix_detalle_ventas_producto_id'), 'detalle_ventas', ['producto_id'], unique=False)
    op.create_index(op.f('ix_detalle_ventas_producto_vendido_id'), 'detalle_ventas', ['producto_vendido_id'], unique=False)
    op.create_index(op.f('ix_detalle_ventas_venta_id'), 'detalle_ventas', ['venta_id'], unique=False)
    op.create_index(op.f('ix_detalle_ventas_venta_item_id'), 'detalle_ventas', ['venta_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_ventas_venta_item_id'), table_name='detalle_ventas')
    op.drop_index(op.f('ix_detalle_ventas_venta_id'), table_name='detalle_ventas')
    op.drop_index(op.f('ix_detalle_ventas_producto_vendido_id'), table_name='detalle_ventas')
    op.drop_index(op.f('ix_detalle_ventas_producto_id'), table_name='detalle_ventas')
    op.drop_index(op.f('ix_detalle_ventas_lote_id'), table_name='detalle_ventas')
    op.drop_table('detalle_ventas')
    op.drop_index(op.f('ix_venta_items_venta_id'), table_name='venta_items')
    op.drop_index(op.f('ix_venta_items_producto_id'), table_name='venta_items')
    op.drop_table('venta_items')
    op.drop_index(op.f('ix_ventas_usuario_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_negocio_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha_hora'), table_name='ventas')
    op.drop_table('ventas')
    op.execute("DROP TYPE IF EXISTS metodopago")
    # ### end Alembic commands ###
