"""fase4_stock_fifo

Revision ID: 1d260ba71b00
Revises: 410cdad33b4c
Create Date: 2026-07-23 16:15:26.747205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d260ba71b00'
down_revision: Union[str, None] = '410cdad33b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_costo_neto', sa.Integer(), nullable=False),
    sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('costo_operacion_prorrateado', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_stock_fecha_ingreso'), 'lotes_stock', ['fecha_ingreso'], unique=False)
    op.create_index(op.f('ix_lotes_stock_negocio_id'), 'lotes_stock', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_lotes_stock_producto_id'), 'lotes_stock', ['producto_id'], unique=False)
    op.create_table('historial_movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA_COMPRA', 'SALIDA_VENTA', 'SALIDA_MERMA', 'AJUSTE_INVENTARIO', name='tipomovimiento'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario_aplicado', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_stock.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_movimientos_fecha_hora'), 'historial_movimientos', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_historial_movimientos_lote_id'), 'historial_movimientos', ['lote_id'], unique=False)
    op.create_index(op.f('ix_historial_movimientos_negocio_id'), 'historial_movimientos', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_historial_movimientos_producto_id'), 'historial_movimientos', ['producto_id'], unique=False)
    op.create_index(op.f('ix_historial_movimientos_tipo_movimiento'), 'historial_movimientos', ['tipo_movimiento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_movimientos_tipo_movimiento'), table_name='historial_movimientos')
    op.drop_index(op.f('ix_historial_movimientos_producto_id'), table_name='historial_movimientos')
    op.drop_index(op.f('ix_historial_movimientos_negocio_id'), table_name='historial_movimientos')
    op.drop_index(op.f('ix_historial_movimientos_lote_id'), table_name='historial_movimientos')
    op.drop_index(op.f('ix_historial_movimientos_fecha_hora'), table_name='historial_movimientos')
    op.drop_table('historial_movimientos')
    op.drop_index(op.f('ix_lotes_stock_producto_id'), table_name='lotes_stock')
    op.drop_index(op.f('ix_lotes_stock_negocio_id'), table_name='lotes_stock')
    op.drop_index(op.f('ix_lotes_stock_fecha_ingreso'), table_name='lotes_stock')
    op.drop_table('lotes_stock')
    op.execute("DROP TYPE IF EXISTS tipomovimiento")
    # ### end Alembic commands ###
