"""fase3_bom_recetas

Revision ID: 410cdad33b4c
Revises: edbdb5e51f40
Create Date: 2026-07-23 15:57:54.924593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410cdad33b4c'
down_revision: Union[str, None] = 'edbdb5e51f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receta_componentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_kit_id', sa.Integer(), nullable=False),
    sa.Column('producto_componente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_componente_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['producto_kit_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_kit_id', 'producto_componente_id', name='uq_receta_kit_componente')
    )
    op.create_index(op.f('ix_receta_componentes_producto_componente_id'), 'receta_componentes', ['producto_componente_id'], unique=False)
    op.create_index(op.f('ix_receta_componentes_producto_kit_id'), 'receta_componentes', ['producto_kit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receta_componentes_producto_kit_id'), table_name='receta_componentes')
    op.drop_index(op.f('ix_receta_componentes_producto_componente_id'), table_name='receta_componentes')
    op.drop_table('receta_componentes')
    # ### end Alembic commands ###
